import { StyleSheet } from "@react-pdf/renderer";

export const exposePdfColors = {
  header: "#0F172A",
  background: "#F8FAFC",
  text: "#1E293B",
  muted: "#64748B",
  border: "#E2E8F0",
  accent: "#334155",
  white: "#FFFFFF",
} as const;

export const exposePdfStyles = StyleSheet.create({
  page: {
    backgroundColor: exposePdfColors.background,
    color: exposePdfColors.text,
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 48,
    paddingBottom: 64,
    paddingHorizontal: 40,
    position: "relative",
  },
  headerBar: {
    backgroundColor: exposePdfColors.header,
    marginHorizontal: -40,
    marginTop: -48,
    paddingHorizontal: 40,
    paddingVertical: 18,
    marginBottom: 24,
  },
  headerTitle: {
    color: exposePdfColors.white,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  headerSubtitle: {
    color: "#CBD5E1",
    fontSize: 8,
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: exposePdfColors.header,
    marginBottom: 10,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: exposePdfColors.border,
  },
  muted: {
    color: exposePdfColors.muted,
    fontSize: 9,
  },
  coverTitle: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: exposePdfColors.header,
    lineHeight: 1.25,
    marginBottom: 6,
  },
  coverSubtitle: {
    fontSize: 11,
    color: exposePdfColors.muted,
    marginBottom: 18,
  },
  heroImage: {
    width: "100%",
    height: 220,
    objectFit: "cover",
    borderRadius: 4,
    marginBottom: 18,
    backgroundColor: exposePdfColors.border,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 16,
  },
  metricBox: {
    width: "48%",
    backgroundColor: exposePdfColors.white,
    borderWidth: 1,
    borderColor: exposePdfColors.border,
    borderRadius: 4,
    padding: 10,
  },
  metricLabel: {
    fontSize: 8,
    color: exposePdfColors.muted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: exposePdfColors.header,
  },
  sellerBadge: {
    marginTop: 8,
    alignSelf: "flex-start",
    backgroundColor: exposePdfColors.header,
    color: exposePdfColors.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 4,
  },
  sellerBadgeLabel: {
    fontSize: 7,
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  sellerBadgeValue: {
    fontSize: 10,
    color: exposePdfColors.white,
  },
  specGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 18,
  },
  specRow: {
    width: "48%",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: exposePdfColors.white,
    borderWidth: 1,
    borderColor: exposePdfColors.border,
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  specLabel: {
    fontSize: 8,
    color: exposePdfColors.muted,
    width: "42%",
  },
  specValue: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    width: "56%",
    textAlign: "right",
  },
  table: {
    borderWidth: 1,
    borderColor: exposePdfColors.border,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 12,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: exposePdfColors.header,
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  tableHeaderCell: {
    color: exposePdfColors.white,
    fontSize: 7.5,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: exposePdfColors.border,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: exposePdfColors.white,
  },
  tableCell: {
    fontSize: 8,
    color: exposePdfColors.text,
  },
  emptyState: {
    padding: 14,
    backgroundColor: exposePdfColors.white,
    borderWidth: 1,
    borderColor: exposePdfColors.border,
    borderRadius: 4,
    color: exposePdfColors.muted,
    fontSize: 9,
  },
  galleryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 18,
  },
  galleryItem: {
    width: "48%",
    height: 130,
    borderRadius: 4,
    objectFit: "cover",
    backgroundColor: exposePdfColors.border,
  },
  dynoImage: {
    width: "100%",
    height: 180,
    objectFit: "contain",
    borderRadius: 4,
    backgroundColor: exposePdfColors.white,
    borderWidth: 1,
    borderColor: exposePdfColors.border,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: exposePdfColors.border,
  },
  totalLabel: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: exposePdfColors.header,
    marginRight: 8,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: exposePdfColors.border,
    paddingTop: 8,
  },
  footerBrand: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: exposePdfColors.header,
    letterSpacing: 0.6,
  },
  footerUrl: {
    fontSize: 7,
    color: exposePdfColors.muted,
    marginTop: 2,
  },
  footerQr: {
    width: 36,
    height: 36,
  },
  pageNumber: {
    fontSize: 8,
    color: exposePdfColors.muted,
  },
});
