import { StyleSheet } from "@react-pdf/renderer";

import {
  exposeColors,
  exposePdfFontFamilies,
  exposeTypography,
} from "@/lib/vehicles/expose-design-tokens";

export const exposePdfColors = exposeColors;

export const exposePdfStyles = StyleSheet.create({
  page: {
    backgroundColor: exposeColors.page,
    color: exposeColors.text,
    fontFamily: exposePdfFontFamilies.body,
    fontSize: exposeTypography.bodySize,
    paddingTop: 44,
    paddingBottom: 72,
    paddingHorizontal: 36,
    position: "relative",
  },
  coverBrandBar: {
    backgroundColor: exposeColors.accent,
    marginHorizontal: -36,
    marginTop: -44,
    paddingHorizontal: 36,
    paddingVertical: 14,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  coverBrandTitle: {
    color: exposeColors.card,
    fontFamily: exposePdfFontFamilies.displayBold,
    fontSize: 9,
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  coverBrandTagline: {
    color: "#a1a1aa",
    fontSize: 7,
    marginTop: 2,
  },
  eyebrow: {
    fontSize: exposeTypography.eyebrowSize,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.textMuted,
    textTransform: "uppercase",
    letterSpacing: exposeTypography.eyebrowTracking,
    marginBottom: 6,
  },
  coverTitle: {
    fontSize: exposeTypography.displayTitleSize,
    fontFamily: exposePdfFontFamilies.displayBold,
    color: exposeColors.text,
    lineHeight: 1.15,
    marginBottom: 6,
  },
  coverFactsLine: {
    fontSize: exposeTypography.coverSubtitleSize,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.textMuted,
    marginBottom: 14,
  },
  coverSubtitle: {
    fontSize: 9,
    color: exposeColors.textMuted,
    marginBottom: 14,
    lineHeight: 1.4,
  },
  heroFrame: {
    width: "100%",
    height: 200,
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 10,
    marginBottom: 14,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  heroImage: {
    width: "92%",
    height: "88%",
    objectFit: "contain",
  },
  trustBadge: {
    backgroundColor: exposeColors.trustBg,
    borderWidth: 1,
    borderColor: exposeColors.trustBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  trustBadgeText: {
    fontSize: 8.5,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.trustTextStrong,
    lineHeight: 1.35,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 14,
  },
  chip: {
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  chipText: {
    fontSize: 7.5,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.text,
  },
  metricsPrimaryRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  metricsSecondaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  metricBoxPrimary: {
    flex: 1,
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 8,
    padding: 12,
  },
  metricBoxSecondary: {
    width: "31%",
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 6,
    padding: 8,
  },
  metricLabel: {
    fontSize: 7,
    color: exposeColors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.9,
    marginBottom: 4,
  },
  metricValuePrimary: {
    fontSize: 14,
    fontFamily: exposePdfFontFamilies.displayBold,
    color: exposeColors.text,
  },
  metricValueSecondary: {
    fontSize: 10,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.text,
  },
  sellerCard: {
    marginTop: 4,
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignSelf: "flex-start",
  },
  sellerLabel: {
    fontSize: 7,
    color: exposeColors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  sellerValue: {
    fontSize: 9.5,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.text,
  },
  innerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: exposeColors.border,
  },
  innerHeaderTitle: {
    fontSize: 11,
    fontFamily: exposePdfFontFamilies.displayBold,
    color: exposeColors.text,
  },
  innerHeaderSubtitle: {
    fontSize: 8,
    color: exposeColors.textMuted,
    maxWidth: "45%",
    textAlign: "right",
  },
  sectionTitle: {
    fontSize: exposeTypography.sectionLabelSize,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  tuevHighlight: {
    fontSize: 9,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.trustText,
    marginBottom: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: exposeColors.trustBg,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  muted: {
    color: exposeColors.textMuted,
    fontSize: 9,
  },
  specGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  specRow: {
    width: "48%",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  specLabel: {
    fontSize: 7.5,
    color: exposeColors.textMuted,
    width: "42%",
  },
  specValue: {
    fontSize: 8.5,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    width: "56%",
    textAlign: "right",
  },
  table: {
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 12,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: exposeColors.tableHeader,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  tableHeaderCell: {
    color: exposeColors.card,
    fontSize: exposeTypography.tableSize,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  tableRow: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: exposeColors.border,
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: exposeColors.card,
    alignItems: "flex-start",
  },
  tableRowAlt: {
    backgroundColor: exposeColors.tableZebra,
  },
  tableCell: {
    fontSize: 7.5,
    color: exposeColors.text,
  },
  tableCellWrap: {
    flexWrap: "wrap",
    lineHeight: 1.35,
  },
  emptyState: {
    padding: 16,
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 8,
    color: exposeColors.textMuted,
    fontSize: 9,
    lineHeight: 1.4,
  },
  galleryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  galleryItem: {
    width: "48%",
    height: 120,
    borderRadius: 8,
    objectFit: "cover",
    backgroundColor: exposeColors.border,
    borderWidth: 1,
    borderColor: exposeColors.border,
  },
  dynoCard: {
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  dynoCaption: {
    fontSize: 7.5,
    color: exposeColors.textMuted,
    marginBottom: 8,
  },
  dynoImage: {
    width: "100%",
    height: 170,
    objectFit: "contain",
  },
  totalCard: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: exposeColors.card,
    borderWidth: 1,
    borderColor: exposeColors.border,
    borderRadius: 8,
    gap: 8,
  },
  totalLabel: {
    fontSize: 9,
    fontFamily: exposePdfFontFamilies.bodyMedium,
    color: exposeColors.textMuted,
  },
  totalValue: {
    fontSize: 10,
    fontFamily: exposePdfFontFamilies.displayBold,
    color: exposeColors.text,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 36,
    right: 36,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: exposeColors.border,
    paddingTop: 8,
  },
  footerLeft: {
    width: "38%",
  },
  footerCenter: {
    width: "24%",
    alignItems: "center",
  },
  footerRight: {
    width: "20%",
    alignItems: "flex-end",
  },
  footerBrand: {
    fontSize: 8,
    fontFamily: exposePdfFontFamilies.displayBold,
    color: exposeColors.text,
    letterSpacing: 0.5,
  },
  footerUrl: {
    fontSize: 6.5,
    color: exposeColors.textMuted,
    marginTop: 2,
  },
  footerMeta: {
    fontSize: 6.5,
    color: exposeColors.textMuted,
    marginTop: 2,
  },
  footerQrLabel: {
    fontSize: 6,
    color: exposeColors.textMuted,
    marginTop: 3,
    textAlign: "center",
  },
  footerQr: {
    width: 40,
    height: 40,
  },
  pageNumber: {
    fontSize: 7.5,
    color: exposeColors.textMuted,
  },
});
