import type { Document, Tag, TagScanResult, Vehicle } from "@/types/database";

/** Demo UUIDs for local development without Supabase. */
export const MOCK_TAG_UUIDS = {
  unclaimed: "demo-unclaimed-tag",
  active: "demo-active-tag",
} as const;

const now = "2026-03-12T10:00:00.000Z";

const mockVehicle: Vehicle = {
  id: "veh_demo_e36",
  user_id: "user_demo",
  make: "BMW",
  model: "328i",
  year: 1995,
  vin: "WBABA9105SAL123456",
  tech_specs: {
    engine: "2.8 M52",
    powerPs: 193,
    powerKw: 142,
    torqueNm: 298,
    displacementCc: 2793,
    fuelType: "Benzin",
    transmission: "5-Gang manuell",
    drivetrain: "Heckantrieb",
    color: "Arctissilber Metallic",
    bodyType: "Coupé",
    notes: "E36 · Widebody · GT-Flügel · KW V1 · BBS LM",
    dynoChartUrl: "/demo/dyno-e36.svg",
  },
  silhouette_image_url: null,
  is_public: false,
  hide_financials: true,
  public_slug: null,
  created_at: now,
  updated_at: now,
};

const mockDocuments: Document[] = [
  {
    id: "doc_abe_1",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "M-Tech Frontspoiler",
    type: "abe",
    file_url: "/demo/abe-frontlippe.pdf",
    vendor: "M-Tech Aerodynamik",
    category: "abe",
    line_items: null,
    kba_number: "ABE KBA 48571",
    vehicle_approvals: ["BMW 3er-Reihe", "BMW 328i E36"],
    authority: "KBA / Hersteller",
    conditions: [
      "Die Montage des Bauteils darf ausschließlich nach der mitgelieferten Einbauanleitung des Herstellers erfolgen. Abweichungen von der vorgesehenen Befestigungsart sind unzulässig.",
      "Die serienmäßigen Befestigungspunkte am Fahrzeug dürfen nicht verändert, aufgebohrt oder geschwächt werden. Beschädigte Aufnahmepunkte sind vor der Montage instand zu setzen.",
      "Nach dem Einbau ist eine Sichtprüfung der Unterbodenfreiheit sowie der sicheren Befestigung aller Schraubverbindungen durchzuführen.",
    ],
    part_category: "Aerodynamik",
    notes:
      "Allgemeine Betriebserlaubnis für den M-Tech Frontspoiler am BMW 3er E36. Montage gemäß Einbauanleitung, Sichtprüfung erforderlich.",
    page_count: 3,
    manufacturer: "M-Tech / AC Schnitzer",
    invoice_number: null,
    mileage_km: 159_400,
    technical_specs: [
      { label: "Material", value: "PU-RIM" },
      { label: "Farbe", value: "Grundiert" },
      { label: "Gewicht", value: "3,2 kg" },
    ],
    approval_fields: {
      kind: "teilegutachten",
      data: {
        testingOrganization: "TÜV",
        documentNumber: "TG-95-3-8821",
        validityArea:
          "Gültig für BMW 3er-Reihe (E36) in Verbindung mit den freigegebenen Rad-/Reifenkombinationen. Montage ausschließlich nach Herstellervorgabe.",
        immediateInspectionRequired: true,
      },
    },
    amount: null,
    date: "2024-03-14",
    created_at: "2024-03-16T10:00:00.000Z",
  },
  {
    id: "doc_invoice_1",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Ölwechsel inkl. Filter",
    type: "invoice",
    file_url: "/demo/invoice-oil.pdf",
    vendor: "BMW Niederlassung Stuttgart",
    category: "service",
    line_items: [
      { label: "Arbeitslohn Ölwechsel", amount: 89 },
      { label: "Motoröl 5W-40 (6,5 l)", amount: 198.5 },
      { label: "Ölfilter-Satz", amount: 42.9 },
      { label: "Entsorgungsgebühr", amount: 16.5 },
      { label: "MwSt. 19 %", amount: 68.4 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RE-2026-0312",
    mileage_km: 178_420,
    technical_specs: null,
    approval_fields: null,
    amount: 415.3,
    date: "2026-03-12",
    created_at: now,
  },
  {
    id: "doc_invoice_oil_2",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Ölwechsel · Castrol Edge 5W-40",
    type: "invoice",
    file_url: "/demo/invoice-oil.pdf",
    vendor: "E36 Spezial · Karlsruhe",
    category: "service",
    line_items: [
      { label: "Arbeitslohn Ölwechsel", amount: 85 },
      { label: "Castrol Edge 5W-40 (6,5 l)", amount: 189 },
      { label: "Ölfilter Mann", amount: 38.5 },
      { label: "Entsorgung Altöl", amount: 14 },
      { label: "MwSt. 19 %", amount: 62.4 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "E36-250218",
    mileage_km: 168_400,
    technical_specs: null,
    approval_fields: null,
    amount: 388.9,
    date: "2025-02-18",
    created_at: "2025-02-18T10:00:00.000Z",
  },
  {
    id: "doc_invoice_oil_3",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Ölwechsel inkl. Filter",
    type: "invoice",
    file_url: "/demo/invoice-oil.pdf",
    vendor: "BMW Autohaus Karlsruhe",
    category: "service",
    line_items: [
      { label: "Servicepauschale Ölwechsel", amount: 92 },
      { label: "BMW Twin Power Turbo 5W-40 (6,5 l)", amount: 204 },
      { label: "Ölfilter-Satz", amount: 44.9 },
      { label: "MwSt. 19 %", amount: 64.5 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RE-2023-1105",
    mileage_km: 154_200,
    technical_specs: null,
    approval_fields: null,
    amount: 405.4,
    date: "2023-11-05",
    created_at: "2023-11-05T10:00:00.000Z",
  },
  {
    id: "doc_invoice_oil_4",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Ölwechsel · Liqui Moly 5W-40",
    type: "invoice",
    file_url: "/demo/invoice-oil.pdf",
    vendor: "KFZ Meisterbetrieb Heilbronn",
    category: "service",
    line_items: [
      { label: "Ölwechsel inkl. Filter", amount: 78 },
      { label: "Liqui Moly Leichtlauf 5W-40 (6,5 l)", amount: 176.5 },
      { label: "Ölfilter", amount: 36.9 },
      { label: "MwSt. 19 %", amount: 55.6 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "KM-211014",
    mileage_km: 134_800,
    technical_specs: null,
    approval_fields: null,
    amount: 347,
    date: "2021-10-14",
    created_at: "2021-10-14T10:00:00.000Z",
  },
  {
    id: "doc_invoice_oil_5",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Ölwechsel · Motul 8100",
    type: "invoice",
    file_url: "/demo/invoice-oil.pdf",
    vendor: "Motorsport Garage Stuttgart",
    category: "service",
    line_items: [
      { label: "Arbeitslohn Ölwechsel", amount: 75 },
      { label: "Motul 8100 X-cess 5W-40 (6,5 l)", amount: 198 },
      { label: "Ölfilter-Satz", amount: 41.5 },
      { label: "MwSt. 19 %", amount: 59.8 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "MSG-200603",
    mileage_km: 119_500,
    technical_specs: null,
    approval_fields: null,
    amount: 374.3,
    date: "2020-06-03",
    created_at: "2020-06-03T10:00:00.000Z",
  },
  {
    id: "doc_invoice_oil_6",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Ölwechsel · Shell Helix",
    type: "invoice",
    file_url: "/demo/invoice-oil.pdf",
    vendor: "BMW Niederlassung Stuttgart",
    category: "service",
    line_items: [
      { label: "Inspektion · Ölwechsel", amount: 82 },
      { label: "Shell Helix Ultra 5W-40 (6,5 l)", amount: 185.5 },
      { label: "Ölfilter", amount: 39.9 },
      { label: "MwSt. 19 %", amount: 58.2 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RE-2018-0321",
    mileage_km: 98_500,
    technical_specs: null,
    approval_fields: null,
    amount: 365.6,
    date: "2018-03-21",
    created_at: "2018-03-21T10:00:00.000Z",
  },
  {
    id: "doc_invoice_2",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "BBS LM 17″ Felgen",
    type: "invoice",
    file_url: "/demo/invoice-carbon.pdf",
    vendor: "BBS Kraftfahrzeugtechnik · Schiltach",
    category: "tuning",
    line_items: [
      { label: "BBS LM 017 17×8 ET35 (Satz)", amount: 2890 },
      { label: "Zentrierringe BMW", amount: 48 },
      { label: "Versand versichert", amount: 59 },
      { label: "MwSt. 19 %", amount: 568.8 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: "Felgen",
    notes: null,
    page_count: 1,
    manufacturer: "BBS",
    invoice_number: "BBS-44102",
    mileage_km: null,
    technical_specs: null,
    approval_fields: null,
    amount: 3565.8,
    date: "2021-03-22",
    created_at: "2021-03-23T10:00:00.000Z",
  },
  {
    id: "doc_invoice_3",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "BBS LM Montage",
    type: "invoice",
    file_url: "/demo/invoice-rays.pdf",
    vendor: "Reifen Müller · Heilbronn",
    category: "service",
    line_items: [
      { label: "Felgenmontage 4×", amount: 88 },
      { label: "Auswuchten", amount: 56 },
      { label: "Reifenmontage 225/45 R17", amount: 96 },
      { label: "Material / Ventile", amount: 28.4 },
      { label: "MwSt. 19 %", amount: 51.2 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RM-210408",
    mileage_km: 128_750,
    technical_specs: null,
    approval_fields: null,
    amount: 319.6,
    date: "2021-04-08",
    created_at: "2021-04-08T10:00:00.000Z",
  },
  {
    id: "doc_invoice_4",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "KW V1 Fahrwerk Einbau",
    type: "invoice",
    file_url: "/demo/invoice-tein.pdf",
    vendor: "E36 Spezial · Karlsruhe",
    category: "tuning",
    line_items: [
      { label: "Arbeitslohn Fahrwerk", amount: 340 },
      { label: "Achsvermessung", amount: 129 },
      { label: "Hilfsstoffe", amount: 28 },
      { label: "MwSt. 19 %", amount: 168.6 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: "Fahrwerk",
    notes: null,
    page_count: 1,
    manufacturer: "KW Automotive",
    invoice_number: "E36-191122",
    mileage_km: 112_600,
    technical_specs: null,
    approval_fields: null,
    amount: 665.6,
    date: "2019-11-22",
    created_at: "2019-11-23T10:00:00.000Z",
  },
  {
    id: "doc_invoice_5",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Bremsen Service VA",
    type: "invoice",
    file_url: "/demo/invoice-brakes.pdf",
    vendor: "BMW Autohaus Karlsruhe",
    category: "service",
    line_items: [
      { label: "Bremsscheiben VA (Satz)", amount: 289 },
      { label: "Bremsbeläge VA", amount: 156 },
      { label: "Bremsflüssigkeit DOT4", amount: 38 },
      { label: "Arbeitslohn", amount: 148 },
      { label: "MwSt. 19 %", amount: 119.7 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RE-2024-0515",
    mileage_km: 162_120,
    technical_specs: null,
    approval_fields: null,
    amount: 750.7,
    date: "2024-05-15",
    created_at: "2024-05-15T10:00:00.000Z",
  },
  {
    id: "doc_invoice_6",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "Remus Sportauspuff Einbau",
    type: "invoice",
    file_url: "/demo/invoice-exhaust.pdf",
    vendor: "Remus Innovation · Künzelsau",
    category: "tuning",
    line_items: [
      { label: "Remus Sportauspuff E36 328i", amount: 890 },
      { label: "Arbeitslohn Auspuff", amount: 180 },
      { label: "Montagematerial", amount: 45 },
      { label: "MwSt. 19 %", amount: 207.4 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: "Abgasanlage",
    notes: null,
    page_count: 1,
    manufacturer: "Remus",
    invoice_number: "REM-22815",
    mileage_km: 141_200,
    technical_specs: null,
    approval_fields: null,
    amount: 1322.4,
    date: "2022-08-15",
    created_at: "2022-08-16T10:00:00.000Z",
  },
  {
    id: "doc_tuev_1",
    vehicle_id: mockVehicle.id,
    user_id: mockVehicle.user_id,
    created_by: mockVehicle.user_id,
    title: "HU/AU bestanden",
    type: "tuev",
    file_url: "/demo/tuev-hu.pdf",
    vendor: "TÜV Süd",
    category: "tuev",
    line_items: null,
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: null,
    mileage_km: 152_880,
    technical_specs: null,
    approval_fields: null,
    amount: null,
    date: "2023-09-18",
    created_at: "2023-09-18T10:00:00.000Z",
  },
];

const mockTags: Record<string, Tag> = {
  [MOCK_TAG_UUIDS.unclaimed]: {
    id: "tag_unclaimed",
    uuid: MOCK_TAG_UUIDS.unclaimed,
    vehicle_id: null,
    status: "unclaimed",
    created_at: now,
    updated_at: now,
  },
  [MOCK_TAG_UUIDS.active]: {
    id: "tag_active",
    uuid: MOCK_TAG_UUIDS.active,
    vehicle_id: mockVehicle.id,
    status: "active",
    created_at: now,
    updated_at: now,
  },
};

export function getMockTagScan(uuid: string): TagScanResult | null {
  const tag = mockTags[uuid];
  if (!tag) return null;

  if (tag.status === "active" && tag.vehicle_id === mockVehicle.id) {
    return {
      tag,
      vehicle: mockVehicle,
      documents: mockDocuments,
    };
  }

  return {
    tag,
    vehicle: null,
    documents: [],
  };
}
