import type { Document, Tag, TagScanResult, Vehicle } from "@/types/database";

/** Demo UUIDs for local development without Supabase. */
export const MOCK_TAG_UUIDS = {
  unclaimed: "demo-unclaimed-tag",
  active: "demo-active-tag",
} as const;

const now = "2026-03-12T10:00:00.000Z";

const mockVehicle: Vehicle = {
  id: "veh_demo_rx8",
  user_id: "user_demo",
  make: "Mazda",
  model: "RX-8",
  year: 2011,
  vin: "JM1FE173XB0300001",
  created_at: now,
  updated_at: now,
};

const mockDocuments: Document[] = [
  {
    id: "doc_abe_1",
    vehicle_id: mockVehicle.id,
    title: "Carbon Frontlippe",
    type: "abe",
    file_url: "/demo/abe-frontlippe.pdf",
    vendor: "Carbon Frontlippe",
    category: "abe",
    line_items: null,
    kba_number: "ABE KBA 12345",
    vehicle_approvals: ["Mazda RX-8", "Mazda RX-8 Spirit R"],
    authority: "KBA / Hersteller",
    conditions: [
      "Die Montage des Bauteils darf ausschließlich nach der mitgelieferten Einbauanleitung des Herstellers erfolgen. Abweichungen von der vorgesehenen Befestigungsart sind unzulässig.",
      "Die serienmäßigen Befestigungspunkte am Fahrzeug dürfen nicht verändert, aufgebohrt oder geschwächt werden. Beschädigte Aufnahmepunkte sind vor der Montage instand zu setzen.",
      "Nach dem Einbau ist eine Sichtprüfung der Unterbodenfreiheit sowie der sicheren Befestigung aller Schraubverbindungen durchzuführen. Lösen sich Teile im Fahrbetrieb, ist das Fahrzeug unverzüglich außer Betrieb zu nehmen.",
    ],
    part_category: "Aerodynamik",
    notes:
      "Allgemeine Betriebserlaubnis für die AutoExe Carbon-Frontlippe am Mazda RX-8. Montage gemäß Einbauanleitung, Sichtprüfung erforderlich.",
    page_count: 3,
    manufacturer: "AutoExe",
    invoice_number: null,
    mileage_km: null,
    amount: null,
    date: "2025-01-14",
    created_at: "2025-01-16T10:00:00.000Z",
  },
  {
    id: "doc_invoice_1",
    vehicle_id: mockVehicle.id,
    title: "Ölwechsel inkl. Filter",
    type: "invoice",
    file_url: "/demo/invoice-oil.pdf",
    vendor: "Mazda Zentrum Stuttgart",
    category: "service",
    line_items: [
      { label: "Arbeitslohn Ölwechsel", amount: 89 },
      { label: "Motoröl 5W-30 (5,0 l)", amount: 198.5 },
      { label: "Ölfilter-Satz", amount: 42.9 },
      { label: "Entsorgungsgebühr", amount: 18.5 },
      { label: "MwSt. 19 %", amount: 80 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RE-2026-0312",
    mileage_km: 67210,
    amount: 428.9,
    date: "2026-03-12",
    created_at: now,
  },
  {
    id: "doc_invoice_2",
    vehicle_id: mockVehicle.id,
    title: "Carbon Frontlippe",
    type: "invoice",
    file_url: "/demo/invoice-carbon.pdf",
    vendor: "AutoExe Europe · Frankfurt",
    category: "tuning",
    line_items: [
      { label: "Carbon Frontlippe RX-8", amount: 1049 },
      { label: "Montage-Kit", amount: 79 },
      { label: "Versand", amount: 29 },
      { label: "MwSt. 19 %", amount: 142 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "AXE-88421",
    mileage_km: null,
    amount: 1299,
    date: "2025-01-08",
    created_at: "2025-01-09T10:00:00.000Z",
  },
  {
    id: "doc_invoice_3",
    vehicle_id: mockVehicle.id,
    title: "RAYS TE37 Montage",
    type: "invoice",
    file_url: "/demo/invoice-rays.pdf",
    vendor: "Felgen & Fahrwerk Stuttgart",
    category: "service",
    line_items: [
      { label: "Felgenmontage 4×", amount: 96 },
      { label: "Auswuchten", amount: 64 },
      { label: "RDKS anlernen", amount: 48 },
      { label: "Material / Ventile", amount: 34.4 },
      { label: "MwSt. 19 %", amount: 70 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RM-241104",
    mileage_km: 64180,
    amount: 312.4,
    date: "2024-11-04",
    created_at: "2024-11-04T10:00:00.000Z",
  },
  {
    id: "doc_invoice_4",
    vehicle_id: mockVehicle.id,
    title: "Tein Sportfedern Einbau",
    type: "invoice",
    file_url: "/demo/invoice-tein.pdf",
    vendor: "Rotary Tuning Garage Heilbronn",
    category: "tuning",
    line_items: [
      { label: "Arbeitslohn Federwechsel", amount: 280 },
      { label: "Achsvermessung", amount: 129 },
      { label: "Hilfsstoffe", amount: 25 },
      { label: "MwSt. 19 %", amount: 155 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RTG-90812",
    mileage_km: 62840,
    amount: 589,
    date: "2024-08-22",
    created_at: "2024-08-23T10:00:00.000Z",
  },
  {
    id: "doc_invoice_5",
    vehicle_id: mockVehicle.id,
    title: "Bremsen Service VA",
    type: "invoice",
    file_url: "/demo/invoice-brakes.pdf",
    vendor: "Mazda Autohaus Karlsruhe",
    category: "service",
    line_items: [
      { label: "Bremsscheiben VA (Satz)", amount: 389 },
      { label: "Bremsbeläge VA", amount: 168 },
      { label: "Bremsflüssigkeit DOT4", amount: 42 },
      { label: "Arbeitslohn", amount: 148 },
      { label: "MwSt. 19 %", amount: 129.2 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RE-2024-0515",
    mileage_km: 60120,
    amount: 876.2,
    date: "2024-05-15",
    created_at: "2024-05-15T10:00:00.000Z",
  },
  {
    id: "doc_invoice_6",
    vehicle_id: mockVehicle.id,
    title: "Racing Beat Abgasanlage",
    type: "invoice",
    file_url: "/demo/invoice-exhaust.pdf",
    vendor: "Racing Beat Europe · Köln",
    category: "tuning",
    line_items: [
      { label: "Racing Beat Exhaust RX-8", amount: 1790 },
      { label: "Montagematerial", amount: 49 },
      { label: "Versand versichert", amount: 39 },
      { label: "MwSt. 19 %", amount: 271 },
    ],
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: "RB-66201",
    mileage_km: null,
    amount: 2149,
    date: "2024-06-02",
    created_at: "2024-06-03T10:00:00.000Z",
  },
  {
    id: "doc_tuev_1",
    vehicle_id: mockVehicle.id,
    title: "HU/AU bestanden",
    type: "tuev",
    file_url: "/demo/tuev-hu.pdf",
    vendor: "TÜV Süd",
    category: "tuev",
    line_items: null,
    kba_number: null,
    vehicle_approvals: null,
    authority: null,
    conditions: null,
    part_category: null,
    notes: null,
    page_count: 1,
    manufacturer: null,
    invoice_number: null,
    mileage_km: null,
    amount: null,
    date: "2024-09-18",
    created_at: now,
  },
];

const mockTags: Record<string, Tag> = {
  [MOCK_TAG_UUIDS.unclaimed]: {
    id: "tag_unclaimed",
    uuid: MOCK_TAG_UUIDS.unclaimed,
    vehicle_id: null,
    status: "unclaimed",
    created_at: now,
    updated_at: now,
  },
  [MOCK_TAG_UUIDS.active]: {
    id: "tag_active",
    uuid: MOCK_TAG_UUIDS.active,
    vehicle_id: mockVehicle.id,
    status: "active",
    created_at: now,
    updated_at: now,
  },
};

export function getMockTagScan(uuid: string): TagScanResult | null {
  const tag = mockTags[uuid];
  if (!tag) return null;

  if (tag.status === "active" && tag.vehicle_id === mockVehicle.id) {
    return {
      tag,
      vehicle: mockVehicle,
      documents: mockDocuments,
    };
  }

  return {
    tag,
    vehicle: null,
    documents: [],
  };
}
